
export const translations = {
  en: {
    // Common UI elements
    "Dashboard": "Dashboard",
    "Guest Management": "Guest Management",
    "Dining & Catering": "Dining & Catering",
    "Event Management": "Event Management", 
    "Finance & Reports": "Finance & Reports",
    "Mobile App": "Mobile App",
    "Membership": "Membership",
    "Human Resources": "Human Resources",
    "Inventory": "Inventory",
    "Reports & Analytics": "Reports & Analytics",
    
    // Buttons and actions
    "Change to Arabic": "Change to Arabic",
    "Change to English": "Change to English",
    "View Details": "View Details",
    "View All": "View All",
    "Add New": "Add New",
    
    // Dashboard stats
    "Active Bookings": "Active Bookings",
    "Pending Orders": "Pending Orders",
    "Upcoming Events": "Upcoming Events",
    "Monthly Revenue": "Monthly Revenue",
    "Pending Renewals": "Pending Renewals",
    "Employees": "Employees",
    "Low Stock Items": "Low Stock Items",
    "Mobile App Users": "Mobile App Users",
    
    // Guest Management
    "ID": "ID",
    "Name": "Name",
    "Rank": "Rank",
    "Room": "Room",
    "Check In": "Check In",
    "Check Out": "Check Out",
    "Status": "Status",
    "Actions": "Actions",
    "Military personnel currently accommodated": "Military personnel currently accommodated",
    
    // Dining & Catering
    "Order Number": "Order Number",
    "Officer": "Officer",
    "Meal": "Meal",
    "Dietary Requirements": "Dietary Requirements",
    "Time Ordered": "Time Ordered",
    "Total Orders": "Total Orders",
    "Orders in Process": "Orders in Process",
    "Average Wait Time": "Average Wait Time",
    "Mess hall and catering orders in process": "Mess hall and catering orders in process",
    "Menu Items": "Menu Items",
    
    // Event Management
    "Event Name": "Event Name",
    "Date": "Date",
    "Attendees": "Attendees",
    "Location": "Location",
    "Total Events": "Total Events",
    "Upcoming": "Upcoming",
    "Total Attendance": "Total Attendance",
    "Scheduled events and trainings": "Scheduled events and trainings",
    "Calendar": "Calendar",
    
    // Finance & Reports
    "Total Revenue": "Total Revenue",
    "Average Room Revenue": "Average Room Revenue",
    "Expenses": "Expenses",
    "Transactions": "Transactions",
    "Amount": "Amount",
    "Transaction Type": "Transaction Type",
    "Department": "Department",
    "Total revenue from all departments": "Total revenue from all departments",
    
    // Mobile App
    "Total Interactions": "Total Interactions", 
    "Unique Users": "Unique Users",
    "Top Device": "Top Device",
    "Engagement Rate": "Engagement Rate",
    "Top Actions": "Top Actions",
    "App Preview": "App Preview",
    "Active users on the ROP mobile platform": "Active users on the ROP mobile platform",
    
    // Membership
    "Active": "Active",
    "Pending Renewal": "Pending Renewal",
    "Expired": "Expired",
    "Renewal Rate": "Renewal Rate",
    "Member Since": "Member Since",
    "Renewal Date": "Renewal Date",
    "Officer memberships requiring renewal": "Officer memberships requiring renewal",
    
    // Human Resources
    "Role": "Role",
    "Attendance": "Attendance",
    "Payroll Status": "Payroll Status",
    "Join Date": "Join Date",
    "Staff across all hotel departments": "Staff across all hotel departments",
    "Department Distribution": "Department Distribution",
    
    // Inventory
    "Item Name": "Item Name", 
    "Quantity": "Quantity",
    "Supplier": "Supplier",
    "Category": "Category",
    "Reorder Level": "Reorder Level",
    "Inventory items requiring restock": "Inventory items requiring restock",
    "Low Stock": "Low Stock",
    
    // Reports & Analytics
    "Report Type": "Report Type",
    "Date Generated": "Date Generated", 
    "Generated By": "Generated By",
    "Create Report": "Create Report",
    "Recent Reports": "Recent Reports",
    "Export": "Export",
    
    // Status terms
    "Confirmed": "Confirmed",
    "Checked In": "Checked In",
    "Checked Out": "Checked Out",
    "Cancelled": "Cancelled",
    "Pending": "Pending",
    "Completed": "Completed",
    "In Progress": "In Progress",
    
    // Data translations
    dataTranslations: {
      // Ranks
      ranks: {
        "Cadet": "Cadet",
        "Officer": "Officer",
        "Command": "Command",
      },
      // Meals
      meals: {
        "Grilled Chicken": "Grilled Chicken",
        "Fish Curry": "Fish Curry",
        "Lamb Biryani": "Lamb Biryani",
        "Vegetable Pasta": "Vegetable Pasta",
        "Beef Burger": "Beef Burger",
        "Caesar Salad": "Caesar Salad",
        "Seafood Platter": "Seafood Platter",
        "Rice and Curry": "Rice and Curry",
      },
      // Dietary options
      dietary: {
        "Halal": "Halal",
        "No restrictions": "No restrictions",
        "Vegetarian": "Vegetarian",
        "Kosher": "Kosher",
        "Low sodium": "Low sodium",
      },
      // Locations
      locations: {
        "Main Hall": "Main Hall",
        "Conference Room A": "Conference Room A",
        "Training Center": "Training Center",
        "Outdoor Court": "Outdoor Court",
        "Executive Suite": "Executive Suite",
      },
    }
  },
  
  ar: {
    // Common UI elements
    "Dashboard": "لوحة القيادة",
    "Guest Management": "إدارة الضيوف",
    "Dining & Catering": "المطعم والضيافة",
    "Event Management": "إدارة الفعاليات", 
    "Finance & Reports": "المالية والتقارير",
    "Mobile App": "تطبيق الهاتف",
    "Membership": "العضويات",
    "Human Resources": "الموارد البشرية",
    "Inventory": "المخزون",
    "Reports & Analytics": "التقارير والتحليلات",
    
    // Buttons and actions
    "Change to Arabic": "التغيير إلى العربية",
    "Change to English": "التغيير إلى الإنجليزية",
    "View Details": "عرض التفاصيل",
    "View All": "عرض الكل",
    "Add New": "إضافة جديد",
    
    // Dashboard stats
    "Active Bookings": "الحجوزات النشطة",
    "Pending Orders": "الطلبات قيد الانتظار",
    "Upcoming Events": "الفعاليات القادمة",
    "Monthly Revenue": "الإيرادات الشهرية",
    "Pending Renewals": "تجديدات معلقة",
    "Employees": "الموظفين",
    "Low Stock Items": "العناصر منخفضة المخزون",
    "Mobile App Users": "مستخدمي التطبيق",
    
    // Guest Management
    "ID": "المعرف",
    "Name": "الاسم",
    "Rank": "الرتبة",
    "Room": "الغرفة",
    "Check In": "تسجيل الدخول",
    "Check Out": "تسجيل الخروج",
    "Status": "الحالة",
    "Actions": "إجراءات",
    "Military personnel currently accommodated": "ضباط الشرطة المقيمين حالياً",
    
    // Dining & Catering
    "Order Number": "رقم الطلب",
    "Officer": "الضابط",
    "Meal": "الوجبة",
    "Dietary Requirements": "متطلبات غذائية",
    "Time Ordered": "وقت الطلب",
    "Total Orders": "إجمالي الطلبات",
    "Orders in Process": "طلبات قيد التنفيذ",
    "Average Wait Time": "متوسط وقت الانتظار",
    "Mess hall and catering orders in process": "طلبات قاعة الطعام والضيافة قيد التنفيذ",
    "Menu Items": "قائمة الطعام",
    
    // Event Management
    "Event Name": "اسم الفعالية",
    "Date": "التاريخ",
    "Attendees": "الحضور",
    "Location": "المكان",
    "Total Events": "إجمالي الفعاليات",
    "Upcoming": "القادمة",
    "Total Attendance": "إجمالي الحضور",
    "Scheduled events and trainings": "الفعاليات والتدريبات المجدولة",
    "Calendar": "التقويم",
    
    // Finance & Reports
    "Total Revenue": "إجمالي الإيرادات",
    "Average Room Revenue": "متوسط إيراد الغرفة",
    "Expenses": "المصروفات",
    "Transactions": "المعاملات",
    "Amount": "المبلغ",
    "Transaction Type": "نوع المعاملة",
    "Department": "القسم",
    "Total revenue from all departments": "إجمالي الإيرادات من جميع الأقسام",
    
    // Mobile App
    "Total Interactions": "إجمالي التفاعلات", 
    "Unique Users": "المستخدمون الفريدون",
    "Top Device": "الجهاز الأكثر استخداماً",
    "Engagement Rate": "معدل التفاعل",
    "Top Actions": "الإجراءات الأكثر شيوعاً",
    "App Preview": "معاينة التطبيق",
    "Active users on the ROP mobile platform": "المستخدمون النشطون على منصة تطبيق شرطة عمان",
    
    // Membership
    "Active": "نشط",
    "Pending Renewal": "قيد التجديد",
    "Expired": "منتهي",
    "Renewal Rate": "معدل التجديد",
    "Member Since": "عضو منذ",
    "Renewal Date": "تاريخ التجديد",
    "Officer memberships requiring renewal": "عضويات الضباط التي تتطلب التجديد",
    
    // Human Resources
    "Role": "الدور",
    "Attendance": "الحضور",
    "Payroll Status": "حالة الرواتب",
    "Join Date": "تاريخ الانضمام",
    "Staff across all hotel departments": "الموظفون في جميع أقسام الفندق",
    "Department Distribution": "توزيع الأقسام",
    
    // Inventory
    "Item Name": "اسم العنصر", 
    "Quantity": "الكمية",
    "Supplier": "المورد",
    "Category": "الفئة",
    "Reorder Level": "مستوى إعادة الطلب",
    "Inventory items requiring restock": "عناصر المخزون التي تتطلب إعادة التخزين",
    "Low Stock": "مخزون منخفض",
    
    // Reports & Analytics
    "Report Type": "نوع التقرير",
    "Date Generated": "تاريخ الإنشاء", 
    "Generated By": "أنشئ بواسطة",
    "Create Report": "إنشاء تقرير",
    "Recent Reports": "التقارير الأخيرة",
    "Export": "تصدير",
    
    // Status terms
    "Confirmed": "مؤكد",
    "Checked In": "تم التسجيل",
    "Checked Out": "تم المغادرة",
    "Cancelled": "ملغي",
    "Pending": "معلق",
    "Completed": "مكتمل",
    "In Progress": "قيد التنفيذ",
    
    // Data translations
    dataTranslations: {
      // Ranks
      ranks: {
        "Cadet": "ضابط متدرب",
        "Officer": "ضابط",
        "Command": "قيادة",
      },
      // Meals
      meals: {
        "Grilled Chicken": "دجاج مشوي",
        "Fish Curry": "كاري السمك",
        "Lamb Biryani": "برياني لحم الضأن",
        "Vegetable Pasta": "معكرونة بالخضار",
        "Beef Burger": "برجر لحم",
        "Caesar Salad": "سلطة سيزر",
        "Seafood Platter": "طبق المأكولات البحرية",
        "Rice and Curry": "أرز مع كاري",
      },
      // Dietary options
      dietary: {
        "Halal": "حلال",
        "No restrictions": "بدون قيود",
        "Vegetarian": "نباتي",
        "Kosher": "كوشر",
        "Low sodium": "قليل الصوديوم",
      },
      // Locations
      locations: {
        "Main Hall": "القاعة الرئيسية",
        "Conference Room A": "غرفة المؤتمرات أ",
        "Training Center": "مركز التدريب",
        "Outdoor Court": "الساحة الخارجية",
        "Executive Suite": "جناح تنفيذي",
      },
    }
  }
};
