
import React from 'react';
import { useNavigate } from 'react-router-dom';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Report } from '@/contexts/DataContext';

interface RecentReportsProps {
  reports: Report[];
}

export function RecentReports({ reports }: RecentReportsProps) {
  const navigate = useNavigate();
  
  return (
    <div className="mt-8">
      <div className="flex justify-between items-center mb-4">
        <h2 className="text-lg font-medium">Recent Reports</h2>
        <Button 
          variant="outline" 
          size="sm" 
          onClick={() => navigate('/reports')}
        >
          View All
        </Button>
      </div>
      <Card>
        <div className="overflow-x-auto">
          <table className="rop-table">
            <thead>
              <tr>
                <th>Report Type</th>
                <th>Date Generated</th>
                <th>Generated By</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {reports.slice(0, 5).map((report) => (
                <tr key={report.id}>
                  <td className="font-medium">{report.type}</td>
                  <td>{report.date}</td>
                  <td>{report.generatedBy}</td>
                  <td>
                    <Button variant="ghost" size="sm">View</Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>
    </div>
  );
}
